/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

/**
 *
 * @author Vukasin Lukic
 */
public class GlavnaForma extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GlavnaForma.class.getName());

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStudenti = new javax.swing.JButton();
        btnZaposleni = new javax.swing.JButton();
        btnSifarnici = new javax.swing.JButton();
        btnObrasci = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuObrasci = new javax.swing.JMenu();
        menuStudenti = new javax.swing.JMenu();
        menuZaposleni = new javax.swing.JMenu();
        menuStudijskiProgram = new javax.swing.JMenu();
        menuTerminDezurstva = new javax.swing.JMenu();
        menuTipPolja = new javax.swing.JMenu();
        menuPodesavanja = new javax.swing.JMenu();
        menuOdjava = new javax.swing.JMenu();
        menuOProgramu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStudenti.setText("btnStudenti");

        btnZaposleni.setText("btnZaposleni");

        btnSifarnici.setText("btnSifarnici");

        btnObrasci.setText("btnObrasci");

        menuObrasci.setText("Obrasci");
        jMenuBar1.add(menuObrasci);

        menuStudenti.setText("Studenti");
        jMenuBar1.add(menuStudenti);

        menuZaposleni.setText("Zaposleni");
        jMenuBar1.add(menuZaposleni);

        menuStudijskiProgram.setText("StudijskiProgrami");
        jMenuBar1.add(menuStudijskiProgram);

        menuTerminDezurstva.setText("TerminDezurstva");
        jMenuBar1.add(menuTerminDezurstva);

        menuTipPolja.setText("TipPolja");
        jMenuBar1.add(menuTipPolja);

        menuPodesavanja.setText("Podesavanja");
        jMenuBar1.add(menuPodesavanja);

        menuOdjava.setText("Odjava");
        jMenuBar1.add(menuOdjava);

        menuOProgramu.setText("O Programu");
        jMenuBar1.add(menuOProgramu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnObrasci, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSifarnici, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudenti, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(581, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnObrasci, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStudenti, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSifarnici, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GlavnaForma().setVisible(true));
    }

    public GlavnaForma(domen.ZaposleniFakulteta ulogovani) {
        initComponents();
        if (ulogovani != null) {
            setTitle("ŠV-20 Sistem - Prijavljeni zaposleni: " + ulogovani.getIme() + " " + ulogovani.getPrezime());
        }
    }

    public void addSV20ObrazacListener(java.awt.event.ActionListener l) {
        menuObrasci.addActionListener(l);
    }

    public void addStudentListener(java.awt.event.ActionListener l) {
        menuStudenti.addActionListener(l);
    }

    public void addZaposleniListener(java.awt.event.ActionListener l) {
        menuZaposleni.addActionListener(l);
    }

    public void addStudijskiProgramListener(java.awt.event.ActionListener l) {
        menuStudijskiProgram.addActionListener(l);
    }

    public void addTerminDezurstvaListener(java.awt.event.ActionListener l) {
        menuTerminDezurstva.addActionListener(l);
    }

    public void addTipPoljaListener(java.awt.event.ActionListener l) {
        menuTipPolja.addActionListener(l);
    }

    public void addPodesavanjaListener(java.awt.event.ActionListener l) {
        menuPodesavanja.addActionListener(l);
    }

    public void addOdjavaListener(java.awt.event.ActionListener l) {
        menuOdjava.addActionListener(l);
    }

    public void addOProgramuListener(java.awt.event.ActionListener l) {
        menuOProgramu.addActionListener(l);
    }

    public void addBtnObrasciListener(java.awt.event.ActionListener l) {
        if (btnObrasci != null) {
            btnObrasci.addActionListener(l);
        }
    }

    public void addBtnStudentiListener(java.awt.event.ActionListener l) {
        if (btnStudenti != null) {
            btnStudenti.addActionListener(l);
        }
    }

    public void addBtnZaposleniListener(java.awt.event.ActionListener l) {
        if (btnZaposleni != null) {
            btnZaposleni.addActionListener(l);
        }
    }

    public void addBtnSifarniciListener(java.awt.event.ActionListener l) {
        if (btnSifarnici != null) {
            btnSifarnici.addActionListener(l);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrasci;
    private javax.swing.JButton btnSifarnici;
    private javax.swing.JButton btnStudenti;
    private javax.swing.JButton btnZaposleni;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuOProgramu;
    private javax.swing.JMenu menuObrasci;
    private javax.swing.JMenu menuOdjava;
    private javax.swing.JMenu menuPodesavanja;
    private javax.swing.JMenu menuStudenti;
    private javax.swing.JMenu menuStudijskiProgram;
    private javax.swing.JMenu menuTerminDezurstva;
    private javax.swing.JMenu menuTipPolja;
    private javax.swing.JMenu menuZaposleni;
    // End of variables declaration//GEN-END:variables
}
