/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

/**
 *
 * @author Vukasin Lukic
 */
public class StavkeObrascaForma extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StavkeObrascaForma.class.getName());

    /**
     * Creates new form StavkeObrascaForma
     */
    public StavkeObrascaForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPolje = new javax.swing.JComboBox();
        txtNivoPodudarnosti = new javax.swing.JTextField();
        txtOcrVrednost = new javax.swing.JTextField();
        txtKorigovanaVrednost = new javax.swing.JTextField();
        chkOcrUspesno = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnSacuvaj = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnOcisti = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbPolje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtNivoPodudarnosti.setText("txtNivoPodudarnosti");

        txtOcrVrednost.setText("txtOcrVrednost");

        txtKorigovanaVrednost.setText("txtKorigovanaVrednost");

        chkOcrUspesno.setText("chkOcrUspesno");

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        btnSacuvaj.setText("btnSacuvaj");

        btnDodaj.setText("btnDodaj");

        btnOcisti.setText("btnOcisti");

        btnObrisi.setText("btnObrisi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKorigovanaVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOcrVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNivoPodudarnosti, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPolje, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkOcrUspesno, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnObrisi))
                                .addGap(785, 785, 785)
                                .addComponent(btnSacuvaj))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnOcisti)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDodaj))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(cmbPolje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtOcrVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtKorigovanaVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtNivoPodudarnosti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkOcrUspesno)
                    .addComponent(btnDodaj)
                    .addComponent(btnOcisti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnObrisi)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                StavkeObrascaForma dialog = new StavkeObrascaForma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JCheckBox chkOcrUspesno;
    private javax.swing.JComboBox cmbPolje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtKorigovanaVrednost;
    private javax.swing.JTextField txtNivoPodudarnosti;
    private javax.swing.JTextField txtOcrVrednost;
    // End of variables declaration//GEN-END:variables
private javax.swing.table.DefaultTableModel tableModel;
    private domen.StavkeObrasca selektovani;

    public StavkeObrascaForma(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        initCustomTableModel();
    }

    private void initCustomTableModel() {
        String[] kolone = {"ID", "Polje", "OCR vrednost", "Korigovana vrednost", "Podudarnost", "OCR uspešno"};
        tableModel = new javax.swing.table.DefaultTableModel(kolone, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblStavke.setModel(tableModel);
    }

    public javax.swing.JTable getTblStavke() {
        return tblStavke;
    }

    public javax.swing.table.DefaultTableModel getTableModel() {
        return tableModel;
    }

    public javax.swing.JComboBox<domen.TipPolja> getCmbPolje() {
        return cmbPolje;
    }

    public javax.swing.JTextField getTxtOcrVrednost() {
        return txtOcrVrednost;
    }

    public javax.swing.JTextField getTxtKorigovanaVrednost() {
        return txtKorigovanaVrednost;
    }

    public javax.swing.JTextField getTxtNivoPodudarnosti() {
        return txtNivoPodudarnosti;
    }

    public javax.swing.JCheckBox getChkOcrUspesno() {
        return chkOcrUspesno;
    }

    public domen.StavkeObrasca getSelektovani() {
        return selektovani;
    }

    public void setSelektovani(domen.StavkeObrasca s) {
        this.selektovani = s;
    }

    public void addDodajListener(java.awt.event.ActionListener l) {
        btnDodaj.addActionListener(l);
    }

    public void addSacuvajListener(java.awt.event.ActionListener l) {
        btnSacuvaj.addActionListener(l);
    }

    public void addObrisiListener(java.awt.event.ActionListener l) {
        btnObrisi.addActionListener(l);
    }

    public void addOcistiListener(java.awt.event.ActionListener l) {
        btnOcisti.addActionListener(l);
    }

    public void addTabelaSelectionListener(javax.swing.event.ListSelectionListener l) {
        tblStavke.getSelectionModel().addListSelectionListener(l);
    }

}
