/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author INSOMNIA
 */
public class FormaKonfiguracijaPort extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormaKonfiguracijaPort.class.getName());

    /**
     * Creates new form FormaKonfiguracijaPort
     */
    public FormaKonfiguracijaPort(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("unesite port:");

        txtPort.addActionListener(this::txtPortActionPerformed);

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(this::btnSacuvajActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnSacuvaj)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSacuvaj)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        int port = -1;

        try {
            port = Integer.parseInt(txtPort.getText());

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Parametri nisu sacuvani.", "Greska", JOptionPane.ERROR_MESSAGE);
        }

        if (port >= 0 && port <= 65535) {
            try {
                konfiguracija.Konfiguracija.getInstanca().setProperty("port", port + "");
                konfiguracija.Konfiguracija.getInstanca().sacuvajIzmene();
                System.out.println("forme.FormaKonfiguracijaPort izvrseno sacuvan port.");
                JOptionPane.showMessageDialog(this, "Parametri su sacuvani.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException ex) {
                System.getLogger(FormaKonfiguracijaPort.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                JOptionPane.showMessageDialog(this, "Parametri nisu sacuvani.", "Greska", JOptionPane.ERROR_MESSAGE);

            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSacuvajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
